[build]
target = "loongarch32-unknown-none-softfloat"

[target.loongarch32-unknown-none]
runner = "qemu-system-loongarch64 -display none -machine virt -cpu la132 -m 4G -serial stdio -kernel"
rustflags = [
    "-C", "link-arg=-Tld.script"
]

[target.loongarch32-unknown-none-softfloat]
runner = "qemu-system-loongarch64 -display none -machine virt -cpu la132 -m 4G -serial stdio -kernel"
rustflags = [
    "-C", "link-arg=-Tld.script"
]
